### ISSUE TITLE
Occasional no case create email 

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#195]
I've not received the first case creation email on more than one occasion, we need to investigate this to understand the cause - Last one I didnt get was for Case #177 29/4/18 17:26

**Comment by mjtko** [comment]
I am also missing emails - I didn't get anything after I added a comment to Case #176 @14:57 or when I resolved the ticket @14.57.

**Comment by jamesremuscat** [comment]
By (current) design, the user creating a case does not get an email notifying them that they have just done so (since they know this, because they've just done so). An email should be sent to other contacts of the site.

Likewise, the user making a comment does not get an email with their own comment in.

Is it possible this is the reason for the "missing" emails?

No emails are currently sent when a case is resolved (or archived/"completed").

**Comment by mjtko** [comment]
I added the comment to #176 as admin-me, but didn't get an email to site-me or see anything to tickets@ -- which something should always go to, right?

**Comment by mjtko** [comment]
I just created #185 (10:36) and no email showing up - no sign of it in sparkpost message events report either.

**Comment by jamesremuscat** [comment]
Yes, something should always get sent to tickets@. SparkPost shows no email events between 13:00 and 14:30 UTC yesterday, perhaps the Flight Center logs will show something.

**Comment by jamesremuscat** [comment]
Fixed (as far as I can tell) in bf5c6181 (and thereafter), by the use of a Redis-backed queue for emails.

Will leave this open until it gets merged to `develop` (to match all the issues that will do so automagically).

**Comment by bobwhitelock** [comment]
Was fixed in #215 I believe :tada:
