### ISSUE TITLE
Suppress RT ticket "N/A" field (at least for users)

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#209]
If possible, to reduce confusion we should not display this field at all.

**Comment by ste78** [comment]
I asked for this, at least we need this until the legacy tickets are cleared out as customers will possibly update legacy tickets in both places and we need a way of linking them.

**Comment by mjtko** [comment]
That seems useful when there is an RT ticket associated.  I'm not sure what the point of displaying "N/A" is when there's no associated ticket tho (i.e. for anything created after go-live) -- seems confusing and easy to suppress.

**Comment by bobwhitelock** [comment]
Decision: do this in next release, have changeover period where this is shown.

**Comment by bobwhitelock** [comment]
@mjtko The above commit, which should soon be merged, makes a change which should make this issue fixed/obsolete, depending on how you look at it. Essentially rather than special casing Cases with RT tickets we will just show similar style identifiers everywhere we need to do so, which will look like `RT12345` for old Cases and `BAR123` for new ones (also see https://trello.com/c/dzY3fb5C/252-new-case-ids-ready-for-use-after-replacing-rt). Since we're doing this everywhere else it makes sense to do this on the Case page, and it should still be obvious what is an RT ticket and what is not from the `RT` prefix. Let me know if you disagree and I can revert this however.
