### ISSUE TITLE
Reset password process broken 

### ISSUE THREAD

**Issue by bobwhitelock** [alces-software/alces-flight-center#256]
Recent changes to how we're sending emails (possibly due to Resque having a different API from what we were using before?) are causing the email sent at the end of the recent password process to not be sent. See https://papertrailapp.com/systems/flight-center-staging/events?focus=932664644638830594&selected=932664644638830594 for the error when this issue occurred.

**Comment by bobwhitelock** [comment]
Also this (and #257) are possibly blocking issues for the next release, since important existing functionality is no longer working.

**Comment by jamesremuscat** [comment]
Here's my hunch:

 - Ruby confusingly says that `reset_password_complete` expects no arguments because we're using `arg1:, arg2:` keyword args in the method signature
- Reqsue's `ActiveRecordSerializer` only supports an array of arguments, not a hash

Observation: all the methods in `CaseMailer` use positional arguments.

Suggested fix: change `reset_password_complete` to use positional arguments.

**Comment by ste78** [comment]
yep, we'll need the fix for this one in the current release on production.
