### ISSUE TITLE
'Other' Service / category / issue for tier 3 comments

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#361]
We're having cases logged under strange categories in order to be able to get a large tier 2 entry box so that they can use it to explain a then unrelated issue. It's difficult to correct this unless we have a place for people to actually put something that they feel doesn't categorise into any of our pre-defined choices. 

I think we've discussed this before but decided to not do it, but I'd like to suggest having an 'Other' -> 'Other' -> 'Other' -> Tier 3 only case that we can ask people to use if they feel their issue really doesn't fit into our categories. Open to any other suggestions that may be easier to implement that still fix the same issue without also encouraging people to not attempt to categorise.

**Comment by mjtko** [comment]
I would approach it something like this:

 * creating any new issue always has it as tier 3 with just an entry for the description
 * if a user makes an effort to make an association with a component or service (or, perhaps, multiple components and/or services), then tier 2 and tier 1 options pop up ("Wow! Such Free!")
 * the interface should somehow encourage users to make the effort :)

The potential problem is that everything starts coming through as tier 3 with just a description, so we'd need to mitigate that somehow, probably.

**Comment by jamesremuscat** [comment]
At this point I think the following is uncontroversial:

- We should allow an "Other / N/A" selection for `Service`, which should correspond to null (e.g. no association with any service)
- We should create an "Other / N/A" `Issue` which only permits tier 3 cases and is always available

I think we can achieve this through data/server changes without needing to change the Elm case form (see ba57e481 for a rough first pass).

One outstanding decision to be made is whether these new "Other" options are the default selections (as Mark's comments suggest, thus by default with no effort customers can raise a tier 3 case) or if we want a "Please choose..." placeholder entry and not display options for any tier until customers actively make a selection (as per Bob's comment). Both would require making (I suspect minimal) changes to the Elm form.

An alternative, that would require larger changes to (or replacement of) the Elm form, would be to allow the same sort of multi-or-non-selection of services/components that we give to admins post-creation. This would also mean we need to rethink the whole way we structure cases, issues, and tiers, and come up with a new approach that makes sense. That's a far bigger change, and conceptual shift, than the relatively straightforward changes discussed above.

**Comment by mjtko** [comment]
Depending on timescales, perhaps we want a bit of both.

I do think we need to consider how cases, issues and tiers are currently structured.  We need a system where users can log a general issue with little effort, but understand that it's immediately chargeable (and authorise use of support credits to achieve resolution). This currently maps to Tier 3, but users tend to stick with Tier 2 and fill the form with a bunch of "N/A"s.

The interface needs to encourage users to provide information in order to reduce the likelihood of a case incurring unnecessary cost. i.e. provide info to qualify for Tier 2 support.

Regarding the options above, I'm not sure whether the first option (inject an "Other" option) goes far enough. However, if it's relatively simple to achieve, let's get that done while we work out how we want to evolve case creation for the longer term.
