### ISSUE TITLE
Case form does not work on Microsoft Edge and IE

### ISSUE THREAD

**Issue by WilliamMcCumstie** [alces-software/alces-flight-center#39]
A new vagrant file has been added to develop. It can be used to launch a Microsoft vm with Edge and IE pre-installed. Please note the vm will have authentication errors as Microsoft does not support ssh. Ignore the errors, the vm should launch in `VirtualBox` gui mode.

The required box can be installed using:
```
vagrant box add https://app.vagrantup.com/Microsoft/boxes/EdgeOnWindows10
```

Once the vm has booted, start the `rails server` on the host machine as per normal for development. This server can be accessed on `10.0.2.2:3000` on the virtual machine. This should auto-magically happen in `VirtualBox`.

When using both `Edge` and `IE` it appears that the case form does not update when the fields change. This means in development, changing from an `advice only` cluster to `fully managed` will not update the form preventing any issues from being logged. Also it means changing a `service`/ `component` does not update the possible issues that can be logged against it.

When the `Edge` developer console is opened, there is a bunch of junk that is being printed including an `XMLHttp` error. Currently we do not believe this junk is related as it does not get reliable reproduced with the issue.

It appears the issue lies within the `elm` form however no more debugging information is available at this time.

**Comment by bobwhitelock** [comment]
@WilliamMcCumstie thanks for starting looking into this - as discussed earlier let's look into this more tomorrow together since I know more about how the `Case` form is put together (since I wrote it).

Can you inline the first section of this issue, about using vagrant to access Flight Center from Edge, in the `Vagrantfile` itself? As if we need to test things out in Edge in future we're more likely to check there than this issue.
