### ISSUE TITLE
My Cases View & Email reminders

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#479]
Have a dedicated page showing all cases related to your user account, grouped if relevant by cluster (rather than per cluster). Against each case we need an indicator showing the time since last update by an Alces admin, and cases should be prioritised in the list based on the last updated time. 

As a secondary feature of this I'd like email sent out every morning with ticket summary, basically an email summarising the my tickets page, which tickets are open and their state.

This ticket is quite similar to #417, a single solution probably covers both.

**Comment by ste78** [comment]
related to #439

**Comment by jamesremuscat** [comment]
- Flight Center homepage for admins should be a list of cases from all sites, ordered chronologically, filtered to the current user.
- A daily cron job should, for each admin, send them this list of cases.
- Need to add "time since last admin update" where "update" is defined as "something which sent the customer an email". Part of implementing this feature is determining which somethings that is :wink: and we'll probably want to revise in the future.

**Comment by jamesremuscat** [comment]
Should the "time since last update" be measured in [business time](https://www.youtube.com/watch?v=WGOohBytKTU) or wallclock time?

**Comment by mjtko** [comment]
Business time seems logical to me.  It's the way we measure response time metrics elsewhere.

Aside: "days" should also take that into account.  i.e. once a response has exceeded 8h, that's 1d.

(A customer may have an out-of-hours SLA which could affect this.  Nothing to worry about immediately, just saying... </requirements from the future>.)

**Comment by jamesremuscat** [comment]
Thanks for that timely comment @mjtko (pun fully intended) - it was made at exactly the right point for me to redefine a day to be eight hours long :slightly_smiling_face: 

Couple more questions:

Does the initial "new case created" email count as an "update by an Alces admin", since it is "something which sent the customer an email"?

I'm assuming that comments added to a case by a customer shouldn't count, even though they are also "something which sent the customer an email"?

**Comment by jamesremuscat** [comment]
Completed in #542.
