### ISSUE TITLE
Asset record / component setup and import refactoring 

### ISSUE THREAD

**Issue by ste78** [alces-software/alces-flight-center#481]
Placeholder for a 2018.7 work, I need @ColonelPanicks to add more detail ;)

1) Import component lists from a cluster script output (benchware?) 
2) Switch the asset record fields to a single markdown page, holding the benchware output at first

**Comment by ColonelPanicks** [comment]
Benchware has the ability to output to markdown, currently waiting for PR approval - https://github.com/alces-software/benchware/pull/2

**Comment by ste78** [comment]
Components would need to be imported from something like this:
```
name: node01
type: server
primary_group: nodes
secondary_groups: compute,all
info: |
## System

| | |
| --- | --- |
| __Bios Version__ | 2.7.1 |
| __Service Tag__ | SERVICE_TAG |

## Interface

| | |
| --- | --- |
| __em1__ | |
| Type | Ethernet |
| State | Up |```

I'm happy to drop all the other stuff we hold on components - component makes, expansions and all that jazz as thats not something we want FlightCenter to need to handle anymore. We just need the basic information so that components can be selected and associated to cases. The markdown info is just there to provide a little more info about a component.

**Comment by jamesremuscat** [comment]
In this model, are groups homogeneous (e.g. everything in the `nodes` group is a `server`) or mixed?

Does `type` mean anything deeper than just a human-readable string identifier?

Are we looking at a single YAML file with multiple component entries, or one YAML file per component?

Is there a purpose in Flight Center for secondary groups or should we ignore these?

**Comment by ColonelPanicks** [comment]
1. 👍 
2. I'm happy to discuss what kind of types you'd like to see. It's currently a manually entered value anyway so once we've established the definitions I can put it into Benchware.
3. A fully populated output can be seen at https://alces.slack.com/archives/C025JHJBP/p1533919351000080
4. 👍

**Comment by jamesremuscat** [comment]
Currently the values of `ComponentType` we have in Flight Center are:
- `Server`
- `Disk array`
- `Network switch`
- `Virtual server`

We also define an ordering on that set, but I'm not sure what value that holds; I think that if Benchware gives a human-readable string for `type` it'll be more than sufficient (as long as there's no possibility of accidentally introducing a `Sever` type because of typos!)

We only use this as flavour text in the UI, we don't even do any sorting by it. (Note that in our data model `ComponentType` is associated with the `ComponentGroup` because of 1. above - so there's redundancy in your current data model which specifies it against every member of the primary group. Fine as long as it's guaranteed to be consistent!)

As @mjtko says, we currently have a pretty name for all `ComponentGroup`s - for example, "Masters" or "GPU nodes". I wonder if it would be at all possible to list groups explicitly in the YAML? Something like:

```yaml
groups:
  masters:
    name: 'Master nodes'
    type: 'Server'
nodes:
  master01:
    primary_group: masters
    secondary_group: NOT-YET-IMPLEMENTED
    info: | 
Informative informations
```
   
This would reduce the repetition of `type` for each group member, and allow us to specify friendly names for groups too. But that might completely mess things up at your end! We could also just use the names you give and allow admins to later specify a "friendly" name for FC only.

From the link that @ColonelPanicks gave, it looks like there's a possible mismatch between the node names we currently have in FC and those in your data source - though the listed nodes don't exist in FC right now, they also don't follow the same naming pattern (FC doesn't have the cluster name as a prefix). That will cause headaches on import.

Speaking of which: we'll have a bunch of existing nodes in FC that we'll want to retain, but update with the new `info` etc. so I'm assuming we'll want data import to be additive, e.g.

```
for each node in import data
    if node exists in FC
        update FC data from import data
    else
        create new node
```

**Comment by mjtko** [comment]
I think the naming of the groups/types is something that should be done FC-side.  I have no problem with that being a post-import task via the admin console for now.  Better might be to enumerate an agreed set of primary groups that FC knows about in order to map to nice names during creation on import -- I think this set is small and consistent enough that this is achievable.  If this seems hard then if need be we can just slam a shrinkwrapped YAML block on the front of the output from benchware or something! 😄 

> they also don't follow the same naming pattern (FC doesn't have the cluster name as a prefix)

The example provided by @ColonelPanicks isn't reflective of the kind of output we'll be expecting to import (in terms of the node names, they will be more like you'd expect, e.g. `node001` etc.)

> I'm assuming we'll want data import to be additive

I think the data import should replace whatever data (`info`) is currently associated with the node:

```
for each node in import data
  if node exists in FC
    replace existing info with info from import data
  else
    create new node
```

**Comment by jamesremuscat** [comment]
If we're confident in the grouping that already exists in FC then we can associate the existing "pretty" group names with the cluster group names being imported. Doesn't help us with future clusters but will smooth the transition process :slightly_smiling_face: 

We currently have 34 unique group names, and we've not been consistent with capitalisation so we have both `Login nodes` and `Login Nodes` for example. I can nevertheless supply this list and allow you to specify which cluster group names get mapped to which, if you'd like?

I'm about to start looking at this, so if there is a newer or more representative set of sample data, now is a good time!
