### ISSUE TITLE
Ensure markdown fields can be edited through admin interface without squishing carriage returns

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#485]
While messy, sometimes it's necessary to change content that is fixed in the user interface by making changes via the admin interface.  In this situation, we should ensure that changes do not cause carriage returns to be dropped as that causes the markdown rendering to break.

The current specific known instance of this is the change request `description` field, though there may be others.

**Comment by bobwhitelock** [comment]
I believe the fix for this would be to add a section like: https://github.com/alces-software/alces-flight-center/blob/185b9bf2db3eda31b7551ce22e605fe897706054/app/models/concerns/admin_config/cluster.rb#L18-L21 to the RailsAdmin config module for this class, and similarly for any other fields we want similar handling for. Note to anyone making this change: editing the RailsAdmin config requires you to restart `rails server` as it doesn't cope well with this.

**Comment by mjtko** [comment]
Also: `case_comment.text`

**Comment by jamesremuscat** [comment]
The underlying cause of losing the carriage returns was the use of `string` field type rather than `text` in a number of places. This was fixed in #549.

Bob's [comment](https://github.com/alces-software/alces-flight-center/issues/485#issuecomment-411361640) changes the default size of the textarea rendered as a result, so is still probably worth doing.

**Comment by mjtko** [comment]
Looks like it's working as I'd expect on staging (i.e. it's showing a textarea for `text` fields) -- didn't realise we'd covered this for 2018.7.

Changing the size is and adding the help is much lower priority than allowing the edits to work as expected in the first place.

**Comment by mjtko** [comment]
I'll open a new issue to track changing the size and close this one off as done via #549.
