### ISSUE TITLE
Last update time not being updated

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#565]
I've created a couple of cases and responded to them, but I'm not seeing that reflected on the case list -- no last update time is being shown:

<img width="1176" alt="screen shot 2018-09-03 at 18 46 21" src="https://user-images.githubusercontent.com/206834/44997957-d86a9e80-afa9-11e8-8f48-6600c41ef4cd.png">

Now that I think about it, it could be cos I'm doing this testing outside business hours, so business time to the response is "0".  However, it should be showing "0" then I think rather than "None"?

**Comment by jamesremuscat** [comment]
An "update" in this situation was defined as "an email was sent to the customer".

At the point of sending an email all we have is a list of email addresses, so rather than hammer the database to retrieve all the relevant user records we infer someone's customer-ness from their email address: anyone with an `@alces-` email address isn't a customer.

When I wrote that heuristic, it didn't occur to me that on staging, _everyone_ has an `@alces-` email address, thus nobody is considered a "customer" (and thus the update time won't be updated). In development everyone's email is set to `@example.com` so this scenario didn't arise.

To support this, we'll have to retain or re-fetch the relevant `User` records and actually check that recipients are not admins.

**Comment by mjtko** [comment]
While not ideal, perhaps a pragmatic thing to do here so we can test the feature is to have a different heuristic in place for staging that considers customer-ness as being anybody with a `center+` email address?
