### ISSUE TITLE
Administrative case escalations

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#566]
> Case is still visible to site contacts, but cannot be interacted with by them. (Possible future: site contact could escalate to tier 3, to be able to comment, but not for now.)

Site contact can currently escalate administrative case from tier 2 to tier 3, but still not interact.  I think we either need:

 * can't escalate and can't interact
 * can escalate, and can then interact -- though that was only a possible future, and I think I prefer the former for now until we see how these kinds of cases work in practice.

> Admin can escalate to tier 2

At the moment administrative cases are created at tier 2, tho they're not really (they're more "internal" than "routine maintenance").  Ideally, I'd not consider these cases having a tier at all, or a different tier.  Once in "tier 2" all usual case semantics should apply (which doesn't seem to be the case at the moment).

**Comment by jamesremuscat** [comment]
> Site contact can currently escalate administrative case from tier 2 to tier 3

That's definitely a bug, the escalate button shouldn't be being shown.

> Ideally, I'd not consider these cases having a tier at all, or a different tier.

Some of the reasoning behind this implementation was given on the PR #557.

It doesn't make much sense in our data model for a case to be created without a tier (nor for an issue to not have a tier, which is a prerequisite of so creating a case).

Supporting either that or a new tier will involve changes to the Elm case form, which I haven't estimated for this iteration: possibly it will need to know both about the administrative tier as a special case and whether or not the current user is an admin - presumably we don't want users to see an unselectable "administrative" tier tab? We'll then need to consider which of the ~25 existing issue types it makes sense to have an "administrative" tier for, and create the new tiers accordingly. We'll also need to change the `case/escalate` endpoint to allow escalations to either tier 2 or tier 3 depending on some criteria.

Because of the large difference in complexity of the two approaches, and the fact that the original requirement wasn't wedded to using tiers to represent this new state (not written on #526 but discussed verbally), I took the view that this was the most sensible solution to the problem. If you now consider that tiers are the way this state should be represented, I would suggest that we pull this feature from this release and re-estimate it for inclusion in 2018.8.

**Comment by mjtko** [comment]
Ok, makes sense. I've read through the notes on the PR and now understand that the way to make it into a "normal" tier 2 is to give it a different issue type -- which is fine by me, it just wasn't discoverable. 😄 

The only thing, that I'd like at this point is (given time constraints) is the suppression of the display of its tier 2 status when in "administrative" mode.

**Comment by mjtko** [comment]
Oh, and the fix of the bug. :bug: :gun:
