### ISSUE TITLE
Add optional site and cluster logos

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#720]
Add some places in the FC UI to accommodate square-shaped logos for site and cluster logos.

These should be optional at each level, and not make things look unusual if they're not present. 😄 

Open to ideas for design and placement: site dashboard, cluster dashboard, as watermarks? etc.

**Comment by benarmston** [comment]
@jamesremuscat @mjtko I'd suggest that we use a similar mechanism to that used at https://gridware.alces-flight.com and https://launch.alces-flight.com so that where we have a cluster or site title we display the logo to the right of it (if the site/cluster has one defined).

Some screen shots:

**Gridware**

![image](https://user-images.githubusercontent.com/287050/46477852-881e7080-c7e3-11e8-88c2-35b728fbdc00.png)

**Launch**

![image](https://user-images.githubusercontent.com/287050/46478070-0f6be400-c7e4-11e8-8b02-b7e631bb636d.png)

**Mockup for FC**

![image](https://user-images.githubusercontent.com/287050/46478584-370f7c00-c7e5-11e8-984b-a29f44ac6844.png)

And something similar for the cluster's overview tab.

If this seems totally wrong (or you have any other comments) let me know.

**Comment by jamesremuscat** [comment]
@benarmston Looks good - we can probably come up with a bunch of other places we'll want the logos to end up but those two (site and cluster overview) are a good starting point.

**Comment by benarmston** [comment]
OK. As long as its not wrong I'll implement that, and we can iterate after.
