### ISSUE TITLE
"No logs to display" when creating log from a case 😕

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#780]
I'm imagining this is a scoping issue of some kind, but I can't really tell.  I'm not sure I expected the list to be empty in this case, or why it is.

Either this needs to more clearly express why the list is empty (scoped, and if so, allow me to somehow change the scope I guess) or always display all the logs -- or at least the most recent few, I can imagine log pagination coming in as a feature request in future!

**Comment by jamesremuscat** [comment]
This is because the page you are taken to is scoped to logs related to the case you just came from. The URL seems to be the only clue that this is the case.

For clarity: by "all the logs" I'm assuming you mean "all the logs associated with the cluster" and not "all the logs related to this case or its current associated components"?

It would make more sense to me to have the "Create a log" button take you to the cluster logs page, pre-filled with case and component associations, which would meet that criteria.

**Comment by mjtko** [comment]
Yup: "all the logs associated with the cluster".

**Comment by jamesremuscat** [comment]
Related question: is being able to see previous logs important when creating a new one?

We've contemplated splitting the "view" and "create" parts of the log page into their own pages, but that would mean you don't see the existing logs when creating a new one.

**Comment by mjtko** [comment]
Sometimes, yes. Though I guess we could do that with tabs.

**Comment by jamesremuscat** [comment]
OK, thanks, will bear that in mind.

This issue fixed by #787.
