### ISSUE TITLE
Related case replaces details rather than adds an initial comment

### ISSUE THREAD

**Issue by mjtko** [alces-software/alces-flight-center#786]
I don't think the UX with related cases is right yet.

I agree that the details may be different or even irrelevant (though, atm, we're preserving the subject (but #785), affected components, issue type) though I feel that , and we do have a reference to the related case, but my expectation when I open a related case is to "port" the key details from the original case (perhaps be able to update them, but not required right now) and add an initial comment.

Perhaps there's a technical reason that means we're doing it the way we are currently?

**Comment by jamesremuscat** [comment]
> though I feel that , and we do have a reference

Is there a missing sentence in the middle of that comment?

I'm not sure I understand what you mean by "port" if not "copy over", or "key details" if not the aspects you list (subject, affected components, issue type). Do you also want the fields from the original case copied over, where at the moment we replace them with a new "details"?

The current implementation matches the requirements agreed in https://docs.google.com/document/d/1nJH4UPo668XhQj6u7Qn-_QfXJtdhSmLe8W2PD8Vdmt8 (rather than a "technical reason").

**Comment by mjtko** [comment]
> Is there a missing sentence in the middle of that comment?

Maybe, don't remember what it is tho!  Possibly I just missed out rewording while editing. 😄 

Yeah, by "port" I mean "copy over".  By "key details" i mean the "case details".

I either missed that the implementation notes in the doc were a mismatch with what I'd suggested on #420 when reviewing the doc or figured it was worth seeing it in the form you'd suggested in those notes before I'd get a good feeling for how it would operate.  My opinion now that I've seen it is that it's not quite right.

The reason I mentioned "a technical reason" is because I'm sensitive to the fact that there has been/is some kind of coupling between the fields that are available and the issue type (not sure of the terminology) so I wondered if that was the reason it had been implemented in that way.

As a further option if copying the case details over and adding a comment is hard for some reason, I'd be happy for the case details to be copied over and an additional "Related case notes" field (or something to that effect) being added.
